/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_admin_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_v1_admin_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Set User Active */
        patch: operations["set_user_active_api_v1_admin_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/admin/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Admin Workflows */
        get: operations["admin_workflows_api_v1_admin_workflows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/workflows/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Workflow
         * @description Enable/disable a queue, promote its rules (À valider sur site -> confirmé) or change
         *     how its activity reaches employees. The event engine itself never changes.
         */
        patch: operations["update_workflow_api_v1_admin_workflows__key__patch"];
        trace?: never;
    };
    "/api/v1/ai/anomalies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Anomalies */
        post: operations["anomalies_api_v1_ai_anomalies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/daily-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Daily Summary */
        post: operations["daily_summary_api_v1_ai_daily_summary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Advisor Status */
        get: operations["advisor_status_api_v1_ai_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard */
        get: operations["dashboard_api_v1_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dossiers/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Dossiers */
        get: operations["search_dossiers_api_v1_dossiers_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dossiers/{dossier_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dossier
         * @description Read-only: opening this endpoint never acknowledges anything.
         */
        get: operations["dossier_api_v1_dossiers__dossier_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dossiers/{dossier_id}/ai/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dossier Summary */
        post: operations["dossier_summary_api_v1_dossiers__dossier_id__ai_summary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dossiers/{dossier_id}/notes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Notes */
        get: operations["notes_api_v1_dossiers__dossier_id__notes_get"];
        put?: never;
        /**
         * Add Note
         * @description Notes are shared at dossier level; ``membership_id`` only adds workflow context.
         */
        post: operations["add_note_api_v1_dossiers__dossier_id__notes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/inbox": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Inbox */
        get: operations["inbox_api_v1_inbox_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memberships/{membership_id}/ai/priority": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Suggest Priority */
        post: operations["suggest_priority_api_v1_memberships__membership_id__ai_priority_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/memberships/{membership_id}/work-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Set Work Status
         * @description Shared work status of one dossier *in one workflow*.
         */
        put: operations["set_work_status_api_v1_memberships__membership_id__work_status_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/occurrences/{occurrence_id}/acknowledge": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Acknowledge
         * @description Opening an occurrence marks its alerts read for the acting employee only.
         */
        post: operations["acknowledge_api_v1_occurrences__occurrence_id__acknowledge_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/occurrences/{occurrence_id}/ai/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Explain Highlight */
        post: operations["explain_highlight_api_v1_occurrences__occurrence_id__ai_explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Session
         * @description Health of the OmegaFlow session. Never exposes cookies, storage state or credentials.
         */
        get: operations["session_api_v1_session_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync Health */
        get: operations["sync_health_api_v1_sync_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request Sync
         * @description Ask the worker for an immediate cycle; the API process never opens the browser.
         */
        post: operations["request_sync_api_v1_sync_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workflows */
        get: operations["workflows_api_v1_workflows_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workflow Detail */
        get: operations["workflow_detail_api_v1_workflows__key__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflows/{key}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workflow Items */
        get: operations["workflow_items_api_v1_workflows__key__items_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AcknowledgeOut */
        AcknowledgeOut: {
            /** Acknowledged */
            acknowledged: number;
            /** Occurrence Id */
            occurrence_id: number;
        };
        /** AdminUserOut */
        AdminUserOut: {
            /** Active */
            active: boolean;
            /** Display Name */
            display_name: string;
            /** Id */
            id: number;
            /** Role */
            role: string;
            /** Username */
            username: string;
        };
        /** AdvisorOutcomeOut */
        AdvisorOutcomeOut: {
            /**
             * Cached
             * @default false
             */
            cached: boolean;
            /** Disclaimer */
            disclaimer: string;
            /**
             * Facts
             * @default []
             */
            facts: string[];
            feature: components["schemas"]["AiFeature"];
            /** Generated At */
            generated_at?: string | null;
            /** Message */
            message?: string | null;
            /** Model */
            model?: string | null;
            /** Result */
            result?: {
                [key: string]: unknown;
            } | null;
            /** Status */
            status: string;
        };
        /** AdvisorStatusOut */
        AdvisorStatusOut: {
            /** Enabled */
            enabled: boolean;
            /** Healthy */
            healthy: boolean | null;
            /** Model */
            model: string | null;
        };
        /**
         * AiFeature
         * @enum {string}
         */
        AiFeature: "DAILY_SUMMARY" | "DOSSIER_SUMMARY" | "HIGHLIGHT_EXPLANATION" | "PRIORITY_SUGGESTION" | "ANOMALY_GROUPING";
        /** ColumnView */
        ColumnView: {
            /** Date */
            date: boolean;
            /** Key */
            key: string;
            /** Kind */
            kind: string;
            /** Label */
            label: string;
        };
        /** CountersView */
        CountersView: {
            /** Actionable New */
            actionable_new: number;
            /** Active Total */
            active_total: number;
            /** By Work Status */
            by_work_status: {
                [key: string]: number;
            };
            /** Changed Unread */
            changed_unread: number;
            /** Problem Workflows */
            problem_workflows: number;
        };
        /** DashboardView */
        DashboardView: {
            /** Activity */
            activity: components["schemas"]["EventOut"][];
            /** Alerts */
            alerts: components["schemas"]["EventOut"][];
            counters: components["schemas"]["CountersView"];
            last_run: components["schemas"]["SyncRunView"] | null;
            session: components["schemas"]["SessionHealthView"];
            /** Workflows */
            workflows: components["schemas"]["WorkflowView"][];
        };
        /** DossierCommonView */
        DossierCommonView: {
            /** Active */
            active: boolean;
            /** City */
            city: string;
            /** Dates */
            dates: components["schemas"]["FieldValue"][];
            /** Detail Error */
            detail_error: string | null;
            /** Dossier Number */
            dossier_number: string;
            /** Estimate Amount Raw */
            estimate_amount_raw: string;
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /** Garage */
            garage: string;
            /** Id */
            id: number;
            /** Insured Name */
            insured_name: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Observation Count */
            observation_count: string;
            /** Portal Status */
            portal_status: string;
            /** Procedure */
            procedure: string;
            /** Record Id */
            record_id: string;
            /** Registration */
            registration: string;
        };
        /** DossierHitView */
        DossierHitView: {
            /** Active */
            active: boolean;
            /** Dossier Id */
            dossier_id: number;
            /** Dossier Number */
            dossier_number: string;
            /** Garage */
            garage: string;
            /** Insured Name */
            insured_name: string;
            /** Portal Status */
            portal_status: string;
            /** Registration */
            registration: string;
            /** Workflows */
            workflows: string[];
        };
        /** DossierView */
        DossierView: {
            dossier: components["schemas"]["DossierCommonView"];
            /** Events */
            events: components["schemas"]["EventOut"][];
            /** Memberships */
            memberships: components["schemas"]["MembershipView"][];
            /** Notes */
            notes: components["schemas"]["NoteView"][];
        };
        /** EventOut */
        EventOut: {
            /** Changed Fields */
            changed_fields: string[];
            /** Changed Labels */
            changed_labels: string[];
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
            /** Dossier Id */
            dossier_id: number | null;
            /** Dossier Number */
            dossier_number: string | null;
            /** Id */
            id: number;
            /** Insured Name */
            insured_name: string | null;
            /** Kind */
            kind: string;
            /** Membership Id */
            membership_id: number | null;
            /** Message */
            message: string | null;
            notification_class: components["schemas"]["NotificationClass"];
            /** Occurrence Id */
            occurrence_id: number | null;
            /** Workflow Key */
            workflow_key: string | null;
            /** Workflow Name */
            workflow_name: string | null;
        };
        /** FacetsView */
        FacetsView: {
            /** Portal Statuses */
            portal_statuses: string[];
            /** Procedures */
            procedures: string[];
            /** Workflows */
            workflows: string[];
        };
        /** FieldValue */
        FieldValue: {
            /**
             * Date
             * @default false
             */
            date: boolean;
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Value */
            value: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ItemPage */
        ItemPage: {
            /** Columns */
            columns?: components["schemas"]["ColumnView"][];
            facets: components["schemas"]["FacetsView"];
            /** Items */
            items: components["schemas"]["ItemView"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** ItemView */
        ItemView: {
            /** Active */
            active: boolean;
            /** City */
            city: string;
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
            /** Dossier Id */
            dossier_id: number;
            /** Dossier Number */
            dossier_number: string;
            /** Fields */
            fields: {
                [key: string]: string;
            };
            /** Garage */
            garage: string;
            /** Insured Name */
            insured_name: string;
            /** Membership Id */
            membership_id: number;
            notification_class: components["schemas"]["NotificationClass"];
            /** Occurrence Id */
            occurrence_id: number;
            /** Occurrence Number */
            occurrence_number: number;
            occurrence_origin: components["schemas"]["OccurrenceOrigin"];
            /** Omegaflow Url */
            omegaflow_url: string;
            /** Portal Status */
            portal_status: string;
            /** Primary Date */
            primary_date: string | null;
            /** Primary Date Label */
            primary_date_label: string | null;
            /** Primary Date Raw */
            primary_date_raw: string;
            /** Procedure */
            procedure: string;
            /** Queue Age Days */
            queue_age_days: number;
            /** Record Id */
            record_id: string;
            /** Registration */
            registration: string;
            rules_status: components["schemas"]["WorkflowRulesStatus"];
            /** Unread */
            unread: boolean;
            /** Unread Kind */
            unread_kind: string | null;
            work_status: components["schemas"]["WorkStatus"];
            /** Work Version */
            work_version: number;
            /** Workflow Category */
            workflow_category: string;
            /** Workflow Key */
            workflow_key: string;
            /** Workflow Name */
            workflow_name: string;
        };
        /** LastRunView */
        LastRunView: {
            /** Baseline */
            baseline: boolean;
            /** Changed */
            changed: number;
            /** Created */
            created: number;
            /** Details Failed */
            details_failed: number;
            /** Left */
            left: number;
            /** Returned */
            returned: number;
            /** Rows Seen */
            rows_seen: number;
            status: components["schemas"]["PollStatus"] | null;
        };
        /** LoginIn */
        LoginIn: {
            /** Password */
            password: string;
            /** Username */
            username: string;
        };
        /** MembershipView */
        MembershipView: {
            /** Active */
            active: boolean;
            /** Current Occurrence Id */
            current_occurrence_id: number;
            /** Fields */
            fields: components["schemas"]["FieldValue"][];
            /**
             * First Seen At
             * Format: date-time
             */
            first_seen_at: string;
            /**
             * Last Seen At
             * Format: date-time
             */
            last_seen_at: string;
            /** Membership Id */
            membership_id: number;
            notification_class: components["schemas"]["NotificationClass"];
            /** Occurrences */
            occurrences: components["schemas"]["OccurrenceView"][];
            /** Omegaflow Url */
            omegaflow_url: string;
            /** Primary Date */
            primary_date: string | null;
            /** Primary Date Raw */
            primary_date_raw: string;
            rules_status: components["schemas"]["WorkflowRulesStatus"];
            work_status: components["schemas"]["WorkStatus"];
            /** Work Updated At */
            work_updated_at: string | null;
            /** Work Updated By */
            work_updated_by: string | null;
            /** Work Version */
            work_version: number;
            /** Workflow Category */
            workflow_category: string;
            /** Workflow Key */
            workflow_key: string;
            /** Workflow Name */
            workflow_name: string;
        };
        /** NoteIn */
        NoteIn: {
            /** Body */
            body: string;
            /** Membership Id */
            membership_id?: number | null;
        };
        /** NoteView */
        NoteView: {
            /** Author */
            author: string;
            /** Body */
            body: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: number;
            /** Membership Id */
            membership_id: number | null;
            /** Workflow Name */
            workflow_name: string | null;
        };
        /**
         * NotificationClass
         * @description How a workflow's activity reaches employees.
         *
         *     ``ACTION`` events can create unread alerts; ``INFORMATIONAL`` events are
         *     only shown in history/summaries; ``SILENT`` workflows are synchronized
         *     for search and detail context and emit no events.
         * @enum {string}
         */
        NotificationClass: "ACTION" | "INFORMATIONAL" | "SILENT";
        /**
         * OccurrenceOrigin
         * @enum {string}
         */
        OccurrenceOrigin: "BASELINE" | "NEW" | "RETURNED";
        /** OccurrenceView */
        OccurrenceView: {
            /**
             * Detected At
             * Format: date-time
             */
            detected_at: string;
            /** Id */
            id: number;
            /** Number */
            number: number;
            origin: components["schemas"]["OccurrenceOrigin"];
            /** Unread */
            unread: boolean;
        };
        /** PollRunView */
        PollRunView: {
            /** Baseline */
            baseline: boolean;
            /** Changed */
            changed: number;
            /** Completed At */
            completed_at: string | null;
            /** Created */
            created: number;
            /** Details Failed */
            details_failed: number;
            /** Error */
            error: string | null;
            /** Id */
            id: number;
            /** Left */
            left: number;
            /** Notifications Created */
            notifications_created: number;
            /** Pages Seen */
            pages_seen: number;
            /** Returned */
            returned: number;
            /** Rows Seen */
            rows_seen: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["PollStatus"];
            /** Sync Run Id */
            sync_run_id: number;
        };
        /**
         * PollStatus
         * @enum {string}
         */
        PollStatus: "COMPLETE" | "PARTIAL" | "AUTH_REQUIRED" | "FAILED";
        /**
         * Role
         * @enum {string}
         */
        Role: "ADMIN" | "EMPLOYEE";
        /** SessionHealthView */
        SessionHealthView: {
            /** Connect Url */
            connect_url: string | null;
            /** Label */
            label: string;
            /** Last Error */
            last_error: string | null;
            /** Last Poll At */
            last_poll_at: string | null;
            /** Last Success At */
            last_success_at: string | null;
            /** State */
            state: string;
            /** Syncing */
            syncing: boolean;
        };
        /** SyncHealthView */
        SyncHealthView: {
            /** Alerts */
            alerts: components["schemas"]["EventOut"][];
            last_run: components["schemas"]["SyncRunView"] | null;
            /** Outbox Pending */
            outbox_pending: number;
            /** Pending Sync Requests */
            pending_sync_requests: number;
            /** Recent Runs */
            recent_runs: components["schemas"]["SyncRunView"][];
            session: components["schemas"]["SessionHealthView"];
            /** Workflows */
            workflows: components["schemas"]["WorkflowView"][];
        };
        /** SyncRequestOut */
        SyncRequestOut: {
            /** Queued */
            queued: boolean;
        };
        /** SyncRunView */
        SyncRunView: {
            /** Completed At */
            completed_at: string | null;
            /** Error */
            error: string | null;
            /** Id */
            id: number;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            status: components["schemas"]["PollStatus"];
            /** Trigger */
            trigger: string;
            /** Workflows Auth Required */
            workflows_auth_required: number;
            /** Workflows Complete */
            workflows_complete: number;
            /** Workflows Failed */
            workflows_failed: number;
            /** Workflows Partial */
            workflows_partial: number;
            /** Workflows Total */
            workflows_total: number;
        };
        /** UserActiveIn */
        UserActiveIn: {
            /** Active */
            active: boolean;
        };
        /** UserCreateIn */
        UserCreateIn: {
            /** Display Name */
            display_name: string;
            /** Password */
            password: string;
            /** @default EMPLOYEE */
            role: components["schemas"]["Role"];
            /** Username */
            username: string;
        };
        /** UserOut */
        UserOut: {
            /** Display Name */
            display_name: string;
            /** Id */
            id: number;
            /** Role */
            role: string;
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WorkStateView */
        WorkStateView: {
            /** Membership Id */
            membership_id: number;
            status: components["schemas"]["WorkStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Updated By */
            updated_by: string | null;
            /** Version */
            version: number;
        };
        /**
         * WorkStatus
         * @enum {string}
         */
        WorkStatus: "TO_DO" | "IN_PROGRESS" | "WAITING" | "DONE";
        /** WorkStatusIn */
        WorkStatusIn: {
            /** Expected Version */
            expected_version?: number | null;
            status: components["schemas"]["WorkStatus"];
        };
        /** WorkflowConfigIn */
        WorkflowConfigIn: {
            /** Enabled */
            enabled?: boolean | null;
            notification_class?: components["schemas"]["NotificationClass"] | null;
            rules_status?: components["schemas"]["WorkflowRulesStatus"] | null;
        };
        /** WorkflowDetailView */
        WorkflowDetailView: {
            /** Columns */
            columns: components["schemas"]["ColumnView"][];
            /** Filter Label */
            filter_label: string | null;
            /** Primary Date Labels */
            primary_date_labels: string[];
            /** Recent Events */
            recent_events: components["schemas"]["EventOut"][];
            /** Recent Runs */
            recent_runs: components["schemas"]["PollRunView"][];
            workflow: components["schemas"]["WorkflowView"];
        };
        /**
         * WorkflowRulesStatus
         * @description Whether employees have approved a workflow's business policy.
         *
         *     ``UNCONFIRMED`` workflows are catalogued but inactive. ``CAPTURE_DERIVED``
         *     workflows run with the conservative queue-membership policy derived from
         *     the ScriptScrap captures and are shown as "À valider sur site" until the
         *     agency validates them. ``CONFIRMED`` workflows were validated by the
         *     agency. Promoting a rule never changes the event engine.
         * @enum {string}
         */
        WorkflowRulesStatus: "UNCONFIRMED" | "CAPTURE_DERIVED" | "CONFIRMED";
        /** WorkflowView */
        WorkflowView: {
            /** Active Count */
            active_count: number;
            /** Baseline Completed At */
            baseline_completed_at: string | null;
            /** By Work Status */
            by_work_status: {
                [key: string]: number;
            };
            /** Category */
            category: string;
            /** Enabled */
            enabled: boolean;
            /** Key */
            key: string;
            /** Last Error */
            last_error: string | null;
            /** Last Poll At */
            last_poll_at: string | null;
            last_poll_status: components["schemas"]["PollStatus"] | null;
            last_run?: components["schemas"]["LastRunView"] | null;
            /** Last Success At */
            last_success_at: string | null;
            /** Name */
            name: string;
            /** Needs Site Validation */
            needs_site_validation: boolean;
            notification_class: components["schemas"]["NotificationClass"];
            /** Route */
            route: string;
            rules_status: components["schemas"]["WorkflowRulesStatus"];
            /** Unread Changed */
            unread_changed: number;
            /** Unread New */
            unread_new: number;
            /** View Id */
            view_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_users_api_v1_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserOut"][];
                };
            };
        };
    };
    create_user_api_v1_admin_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_user_active_api_v1_admin_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserActiveIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    admin_workflows_api_v1_admin_workflows_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowView"][];
                };
            };
        };
    };
    update_workflow_api_v1_admin_workflows__key__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowConfigIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    anomalies_api_v1_ai_anomalies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvisorOutcomeOut"];
                };
            };
        };
    };
    daily_summary_api_v1_ai_daily_summary_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvisorOutcomeOut"];
                };
            };
        };
    };
    advisor_status_api_v1_ai_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvisorStatusOut"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    dashboard_api_v1_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardView"];
                };
            };
        };
    };
    search_dossiers_api_v1_dossiers_search_get: {
        parameters: {
            query: {
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DossierHitView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dossier_api_v1_dossiers__dossier_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dossier_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DossierView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dossier_summary_api_v1_dossiers__dossier_id__ai_summary_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dossier_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvisorOutcomeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    notes_api_v1_dossiers__dossier_id__notes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dossier_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_note_api_v1_dossiers__dossier_id__notes_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                dossier_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoteIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoteView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    inbox_api_v1_inbox_get: {
        parameters: {
            query?: {
                workflow?: string[] | null;
                category?: string | null;
                search?: string | null;
                unread?: boolean;
                kind?: string | null;
                work_status?: components["schemas"]["WorkStatus"] | null;
                portal_status?: string | null;
                procedure?: string | null;
                sort?: string;
                order?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    suggest_priority_api_v1_memberships__membership_id__ai_priority_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                membership_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvisorOutcomeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_work_status_api_v1_memberships__membership_id__work_status_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                membership_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkStatusIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkStateView"];
                };
            };
            /** @description Le statut a été modifié entre-temps. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    acknowledge_api_v1_occurrences__occurrence_id__acknowledge_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                occurrence_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AcknowledgeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    explain_highlight_api_v1_occurrences__occurrence_id__ai_explain_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                occurrence_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdvisorOutcomeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    session_api_v1_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionHealthView"];
                };
            };
        };
    };
    sync_health_api_v1_sync_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncHealthView"];
                };
            };
        };
    };
    request_sync_api_v1_sync_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncRequestOut"];
                };
            };
        };
    };
    workflows_api_v1_workflows_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowView"][];
                };
            };
        };
    };
    workflow_detail_api_v1_workflows__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowDetailView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    workflow_items_api_v1_workflows__key__items_get: {
        parameters: {
            query?: {
                search?: string | null;
                unread?: boolean;
                kind?: string | null;
                work_status?: components["schemas"]["WorkStatus"] | null;
                portal_status?: string | null;
                procedure?: string | null;
                sort?: string;
                order?: string;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ItemPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
