"""initial schema

Revision ID: c22e2bb290df
Revises: 
Create Date: 2026-09-15 23:59:26.163613

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c22e2bb290df'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None

_PORTAL_ACCOUNTS = sa.table(
    "portal_accounts",
    sa.column("id", sa.Integer),
    sa.column("name", sa.String),
    sa.column("base_url", sa.String),
    sa.column("enabled", sa.Boolean),
    sa.column("baseline_completed_at", sa.DateTime(timezone=True)),
    sa.column("session_status", sa.String),
    sa.column("last_poll_at", sa.DateTime(timezone=True)),
    sa.column("last_success_at", sa.DateTime(timezone=True)),
    sa.column("last_error", sa.String),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portal_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('baseline_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_status', sa.String(length=20), nullable=False),
    sa.Column('last_poll_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('dossiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_account_id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.String(length=64), nullable=False),
    sa.Column('dossier_number', sa.String(length=200), nullable=False),
    sa.Column('insured_name', sa.String(length=300), nullable=False),
    sa.Column('procedure', sa.String(length=200), nullable=False),
    sa.Column('registration', sa.String(length=100), nullable=False),
    sa.Column('garage', sa.String(length=300), nullable=False),
    sa.Column('estimate_amount_raw', sa.String(length=100), nullable=False),
    sa.Column('portal_status', sa.String(length=200), nullable=False),
    sa.Column('city', sa.String(length=200), nullable=False),
    sa.Column('observation_count', sa.String(length=50), nullable=False),
    sa.Column('agreement_login', sa.String(length=200), nullable=False),
    sa.Column('details_href', sa.String(length=1000), nullable=False),
    sa.Column('date_creation', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_creation_raw', sa.String(length=100), nullable=False),
    sa.Column('date_premiere_fin_prevue', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_premiere_fin_prevue_raw', sa.String(length=100), nullable=False),
    sa.Column('date_fin_travaux_prevue', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_fin_travaux_prevue_raw', sa.String(length=100), nullable=False),
    sa.Column('date_envoi_devis_garage', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_envoi_devis_garage_raw', sa.String(length=100), nullable=False),
    sa.Column('date_photos_avant', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_photos_avant_raw', sa.String(length=100), nullable=False),
    sa.Column('detail_complete', sa.Boolean(), nullable=False),
    sa.Column('detail_error', sa.String(length=1000), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('missing_complete_polls', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portal_account_id'], ['portal_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portal_account_id', 'record_id', name='uq_dossier_account_record')
    )
    op.create_index('ix_dossier_active', 'dossiers', ['portal_account_id', 'active'], unique=False)
    op.create_table('poll_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portal_account_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rows_seen', sa.Integer(), nullable=False),
    sa.Column('pages_seen', sa.Integer(), nullable=False),
    sa.Column('details_failed', sa.Integer(), nullable=False),
    sa.Column('error', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['portal_account_id'], ['portal_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_poll_runs_portal_account_id'), 'poll_runs', ['portal_account_id'], unique=False)
    op.create_table('dossier_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=2000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('length(body) <= 2000', name='ck_note_max_length'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dossier_notes_dossier_id'), 'dossier_notes', ['dossier_id'], unique=False)
    op.create_table('dossier_work',
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('dossier_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_dossier_id'), 'notifications', ['dossier_id'], unique=False)
    op.create_table('notification_reads',
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id', 'user_id')
    )
    # ### end Alembic commands ###

    # Seed the single shared OmegaFlow portal account (see docs/omegaflow-contract.md).
    op.bulk_insert(
        _PORTAL_ACCOUNTS,
        [
            {
                "name": "OmegaFlow",
                "base_url": "https://omegaflow.ma",
                "enabled": True,
                "baseline_completed_at": None,
                "session_status": "UNKNOWN",
                "last_poll_at": None,
                "last_success_at": None,
                "last_error": None,
            }
        ],
    )


def downgrade() -> None:
    op.execute(_PORTAL_ACCOUNTS.delete())
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_reads')
    op.drop_index(op.f('ix_notifications_dossier_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('dossier_work')
    op.drop_index(op.f('ix_dossier_notes_dossier_id'), table_name='dossier_notes')
    op.drop_table('dossier_notes')
    op.drop_index(op.f('ix_poll_runs_portal_account_id'), table_name='poll_runs')
    op.drop_table('poll_runs')
    op.drop_index('ix_dossier_active', table_name='dossiers')
    op.drop_table('dossiers')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_table('portal_accounts')
    # ### end Alembic commands ###
